; =============================== CONFIGS ===============================

[BASE]
build_flags =
  -D OPENKNX
  -D NCN5120
  -D KNX_FLASH_CALLBACK
  -D SMALL_GROUPOBJECT
  -D USE_BINSEARCH
  -D KNX_ACTIVITYCALLBACK
  -Iinclude
  -Ilib/OGM-HardwareConfig/include/
  -Wuninitialized
  -Wunused-variable
  -Wno-unknown-pragmas 
  -Wno-switch
debug_build_flags = 
  -ggdb3
  -O0

[KNX_TP]
build_flags =
  -D MASK_VERSION=0x07B0

[KNX_IP]
build_flags =
  -D MASK_VERSION=0x57B0

[KNX_IPTP]
build_flags =
  -D MASK_VERSION=0x091A

[UPLOAD_JLINK]
upload_protocol = jlink

[OPENKNX_DEBUG]
build_flags =
  -D OPENKNX_DEBUG
  
; =============================== BASE ===============================

[env]
framework = arduino
monitor_speed = 115200
monitor_filters =
  direct
lib_ldf_mode = chain
debug_tool = jlink
debug_extra_cmds = 
  set output-radix 16
extra_scripts =
  lib/OGM-Common/scripts/pio/prepare.py
  lib/OGM-Common/scripts/pio/show_flash_partitioning.py