"""
Open ■
┬────┴  clean_idf_artifacts
■ KNX   2026 OpenKNX - Erkan Çolak

PlatformIO extra_script: clean_idf_artifacts.py
Removes IDF-generated artifacts when `pio run --target clean` is executed.
"""
Import("env")
import os
import shutil

# Guard: only run for IDF environments that build custom IDF libs.
# Detection marker: custom_idf_build = true must be set DIRECTLY in [env:*].
# Envs without this flag (e.g. Adafruit Arduino envs) are skipped.
try:
    flag = env.GetProjectOption("custom_idf_build", default=None)
    if not flag or str(flag).strip().lower() not in ("1", "true", "yes"):
        Return()
except Exception:
    Return()

if not env.GetOption("clean"):
    Return()  # Only active during --target clean

PROJECT_DIR = env.subst("$PROJECT_DIR")
ENV_NAME    = env.subst("$PIOENV")

extra_clean = [
    # sdkconfig (no suffix): IDF-generated merged config cache in the project root.
    os.path.join(PROJECT_DIR, "sdkconfig"),
    # sdkconfig.defaults: pioarduino TASMOTA hash header.
    # WARNING: deleting this forces a full IDF lib rebuild on the next build (~30-60 min).
    os.path.join(PROJECT_DIR, "sdkconfig.defaults"),
    os.path.join(PROJECT_DIR, "managed_components"),
    os.path.join(PROJECT_DIR, ".dummy"),
    os.path.join(PROJECT_DIR, "dependencies.lock"),
    os.path.join(PROJECT_DIR, "CMakeLists.txt"),
    # src/CMakeLists.txt: also generated by pioarduino (registers src/ as IDF app component).
    os.path.join(PROJECT_DIR, "src", "CMakeLists.txt"),
    # idf_component.yml: generated by setup_idf_components.py, not committed.
    os.path.join(PROJECT_DIR, "idf_component.yml"),
]

# Generated components/ subdirs (NOT components/certs/ -- manually maintained + committed).
# Everything under components/ except 'certs' was created by setup_idf_components.py.
COMPONENTS_DIR = os.path.join(PROJECT_DIR, "components")
if os.path.isdir(COMPONENTS_DIR):
    for subdir in os.listdir(COMPONENTS_DIR):
        if subdir == "certs":
            continue  # components/certs/ is committed -- NEVER delete
        subpath = os.path.join(COMPONENTS_DIR, subdir)
        if os.path.isdir(subpath):
            extra_clean.append(subpath)

# sdkconfig.<envname> files: generated by pre_generate_crt_asm.py from INI values, not committed.
for fname in os.listdir(PROJECT_DIR):
    if fname.startswith("sdkconfig.") and fname != "sdkconfig.defaults":
        fpath = os.path.join(PROJECT_DIR, fname)
        if os.path.isfile(fpath):
            extra_clean.append(fpath)

print(f"\n[clean_idf] Cleaning IDF artifacts for '{ENV_NAME}' ...")
for path in extra_clean:
    if os.path.exists(path):
        print(f"[clean_idf]  Deleting: {os.path.relpath(path, PROJECT_DIR)}")
        if os.path.isdir(path):
            shutil.rmtree(path, ignore_errors=True)
        else:
            os.remove(path)
    else:
        print(f"[clean_idf]  (not found): {os.path.relpath(path, PROJECT_DIR)}")
print("[clean_idf] Done.\n")
